package view;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import models.attendance_mod;
import models.query;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hima1993
 */
public class Attendance extends javax.swing.JFrame {

    /**
     * Creates new form Attendance
     */
    public Attendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        attd_numberofdays = new javax.swing.JTextField();
        attd_emp_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        attd_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        attd_show = new javax.swing.JButton();
        attd_clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        attd_submit = new javax.swing.JButton();
        attd_main = new javax.swing.JButton();
        attd_date = new com.toedter.calendar.JDateChooser();
        attd_to = new com.toedter.calendar.JDateChooser();
        attd_from = new com.toedter.calendar.JDateChooser();
        attd_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel9.setText("Number of Days");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel10.setText("Employee ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel12.setText("To");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        attd_numberofdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attd_numberofdaysActionPerformed(evt);
            }
        });
        getContentPane().add(attd_numberofdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 60, 40));

        attd_emp_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                attd_emp_idKeyPressed(evt);
            }
        });
        getContentPane().add(attd_emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 40, 30));

        attd_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Attendance Date"
            }
        ));
        attd_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attd_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(attd_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 370, 450));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Attendance ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 390, 490));

        attd_show.setBackground(new java.awt.Color(102, 102, 255));
        attd_show.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        attd_show.setText("Show Attendance");
        attd_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attd_showActionPerformed(evt);
            }
        });
        getContentPane().add(attd_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, 50));

        attd_clear.setBackground(new java.awt.Color(102, 102, 255));
        attd_clear.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        attd_clear.setText("Clear");
        attd_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attd_clearActionPerformed(evt);
            }
        });
        getContentPane().add(attd_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 90, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Employee Attendance");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel13.setText("Attendance Date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel14.setText("From");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, 20));

        attd_submit.setBackground(new java.awt.Color(102, 102, 255));
        attd_submit.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        attd_submit.setText("Submit");
        attd_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attd_submitActionPerformed(evt);
            }
        });
        getContentPane().add(attd_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 90, 40));

        attd_main.setBackground(new java.awt.Color(255, 204, 255));
        attd_main.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        attd_main.setText("Main Menu");
        attd_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attd_mainActionPerformed(evt);
            }
        });
        getContentPane().add(attd_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 140, 20));
        getContentPane().add(attd_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, 40));
        getContentPane().add(attd_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 140, 40));
        getContentPane().add(attd_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 40));

        attd_delete.setBackground(new java.awt.Color(102, 102, 255));
        attd_delete.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        attd_delete.setText("Delete");
        attd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attd_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(attd_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attd_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attd_showActionPerformed
        
        attendance_mod attd = new attendance_mod();
        attd.attd_emp_id = attd_emp_id.getText();
        attd.attd_from=(java.util.Date) attd_from.getDate();

        attd.attd_to=(java.util.Date) attd_to.getDate();
        
        int a = attd.show(attd_table);
        attd_numberofdays.setText(a+"");
        /*try {
            
            DefaultTableModel model = (DefaultTableModel) attd_table.getModel();
            model.setRowCount(0);
            DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            int attendances_id = 0;
            int e_id = 0;
            String attendance_date = null;

            ResultSet k = query.thequery_search("select * from employee_has_attendance where employee_emp_id='" + attd_emp_id.getText() + "'");

            while (k.next()) {
                attendances_id = k.getInt("attendance_attendance_id");
                e_id = k.getInt("employee_emp_id");
                System.out.println("came");

                System.out.println(attendances_id);
                ResultSet h = query.thequery_search("select * from attendance where attendance_id='" + attendances_id + "' and date between '" + fmt.format(this.attd_from.getDate()) + "' and '" + fmt.format(this.attd_to.getDate()) + "'");

                while (h.next()) {
                    e_id = k.getInt("employee_emp_id");
                    attendance_date = fmt.format(h.getDate("date"));
                    Date date = fmt.parse(attendance_date);
                    model.addRow(new Object[]{e_id, attendance_date});

                }
            }

            attd_numberofdays.setText(attd_table.getRowCount() + "");
        } catch (Exception ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }*/


    }//GEN-LAST:event_attd_showActionPerformed

    private void attd_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attd_clearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) attd_table.getModel();
        model.setRowCount(0);
        attd_emp_id.setText("");

        attd_numberofdays.setText("");
        attd_date.setCalendar(null);
        attd_to.setCalendar(null);
        attd_from.setCalendar(null);

    }//GEN-LAST:event_attd_clearActionPerformed

    private void attd_numberofdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attd_numberofdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attd_numberofdaysActionPerformed

    private void attd_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attd_submitActionPerformed
        attendance_mod attd = new attendance_mod();
        attd.attd_emp_id = attd_emp_id.getText();
        attd.attd_from=(java.util.Date) attd_from.getDate();

        attd.attd_to=(java.util.Date) attd_to.getDate();
        attd.attd_date = (java.util.Date) attd_date.getDate();
        attd.submit(attd_table);
       /* try {

            JOptionPane.showMessageDialog(rootPane, "Attendance Submitted Sucessfully.", "attendance submit", JOptionPane.INFORMATION_MESSAGE);
            DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            String date = fmt.format(this.attd_date.getDate());

            query.thequery("insert into attendance (date) values('" + date + "')");
            int attd = 0;
            ResultSet l = query.thequery_search("select max(attendance_id)as attd_id from attendance");
            if (l.next()) {
                attd = l.getInt("attd_id");
            }

            int pr_emp = 0;
            ResultSet m = query.thequery_search("select person_person_id from employee where emp_id='" + attd_emp_id.getText() + "'");
            if (m.next()) {
                pr_emp = m.getInt("person_person_id");
            }
            query.thequery("insert into employee_has_attendance (attendance_attendance_id,employee_emp_id) values('" + attd + "','" + attd_emp_id.getText() + "')");

            DefaultTableModel model = (DefaultTableModel) attd_table.getModel();

            model.addRow(new Object[]{attd_emp_id.getText(), date});
            attd_emp_id.setText("");

            attd_numberofdays.setText("");
            attd_date.setCalendar(null);
            attd_to.setCalendar(null);
            attd_from.setCalendar(null);
        } catch (Exception ex) {
            ex.printStackTrace();
        }*/
    }//GEN-LAST:event_attd_submitActionPerformed

    private void attd_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attd_mainActionPerformed
        menu mn = new menu();
        mn.setVisible(true);
        close();
    }//GEN-LAST:event_attd_mainActionPerformed

    private void attd_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attd_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) attd_table.getModel();
        DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        int i = attd_table.getSelectedRow();
        if (i >= 0) {
            try {
                attd_emp_id.setText(model.getValueAt(i, 0).toString());
                Date date = fmt.parse(model.getValueAt(i, 1).toString());
                attd_date.setDate(date);

            } catch (ParseException ex) {
                Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_attd_tableMouseClicked

    private void attd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attd_deleteActionPerformed
       int p = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want To Delete This", "service delete", JOptionPane.YES_NO_OPTION);
        if (p == JOptionPane.YES_OPTION) { 
        attendance_mod attd = new attendance_mod();
        attd.attd_emp_id = attd_emp_id.getText();
        attd.attd_from=(java.util.Date) attd_from.getDate();

        attd.attd_to=(java.util.Date) attd_to.getDate();
        attd.attd_date = (java.util.Date) attd_date.getDate();
        
        attd.delete(attd_table);
        
        /*try {
            // TODO add your handling code here:
            DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            String date = fmt.format(this.attd_date.getDate());
              int attd = 0;
              int emp =0;
            ResultSet l = query.thequery_search("select attendance_id as attd_id from attendance where date ='" + date + "' ");
            System.out.println(date);
        if (l.next()) {
                attd = l.getInt("attd_id");
                System.out.println(attd);
            }
            ResultSet m = query.thequery_search("select empadd as emp_id from employee_has_attendance where attendance_attendance_id ='" + attd + "' and employee_emp_id='"+attd_emp_id.getText()+"'");
        if(m.next()){
        emp = m.getInt("emp_id");
        System.out.println(emp);
        
        }
        query.thequery("delete from employee_has_attendance where empadd='"+emp+"' ");
        query.thequery("delete from attendance where attendance_id='"+attd+"' ");

        } catch (Exception ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }*/

        
            

            attd_emp_id.setText("");
            attd_numberofdays.setText("");
            attd_date.setCalendar(null);
            attd_to.setCalendar(null);
            attd_from.setCalendar(null);

    }//GEN-LAST:event_attd_deleteActionPerformed
    }
    private void attd_emp_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_attd_emp_idKeyPressed
        // TODO add your handling code here:
        int key = evt.getExtendedKeyCode();
        if (key >= evt.VK_0 && key <= evt.VK_9 || key == KeyEvent.VK_BACK_SPACE || key == KeyEvent.VK_DELETE || key >= evt.VK_A && key <= evt.VK_Z) {
            attd_emp_id.setEditable(true);

        } else {
            attd_emp_id.setEditable(false);

        }

    }//GEN-LAST:event_attd_emp_idKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance().setVisible(true);
            }
        });
    }

    private void close() {
        WindowEvent winclosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosing);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attd_clear;
    private com.toedter.calendar.JDateChooser attd_date;
    private javax.swing.JButton attd_delete;
    private javax.swing.JTextField attd_emp_id;
    private com.toedter.calendar.JDateChooser attd_from;
    private javax.swing.JButton attd_main;
    private javax.swing.JTextField attd_numberofdays;
    private javax.swing.JButton attd_show;
    private javax.swing.JButton attd_submit;
    private javax.swing.JTable attd_table;
    private com.toedter.calendar.JDateChooser attd_to;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
