/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import models.payment_mod;
import models.query;

/**
 *
 * @author hima1993
 */
public class payment extends javax.swing.JFrame {

    /**
     * Creates new form payment
     */
    public payment() {
        initComponents();
    }
    public void set(String fname,String lname){
    pay_p_fname.setText(fname);
    pay_p_lname.setText(lname);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pay_main = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        pay_adm_id = new javax.swing.JTextField();
        pay_p_lname = new javax.swing.JTextField();
        pay_p_fname = new javax.swing.JTextField();
        pay_balance = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pay_print = new javax.swing.JButton();
        pay_clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pay = new javax.swing.JTable();
        Payement = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pay_payment = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pay_subtotal = new javax.swing.JTextField();
        pay_balance_but = new javax.swing.JButton();
        pay_show1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        test_result = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Payment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel8.setText("Balance");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel10.setText("Admission ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        pay_main.setBackground(new java.awt.Color(255, 204, 255));
        pay_main.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        pay_main.setText("Main Menu");
        pay_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_mainActionPerformed(evt);
            }
        });
        getContentPane().add(pay_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 140, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel11.setText("Patient Surname");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        getContentPane().add(pay_adm_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 40, 30));

        pay_p_lname.setEditable(false);
        pay_p_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_p_lnameActionPerformed(evt);
            }
        });
        getContentPane().add(pay_p_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, 30));

        pay_p_fname.setEditable(false);
        pay_p_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_p_fnameActionPerformed(evt);
            }
        });
        getContentPane().add(pay_p_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 120, 30));

        pay_balance.setText("0.00");
        pay_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_balanceActionPerformed(evt);
            }
        });
        getContentPane().add(pay_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 80, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel12.setText("Patient Initials");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel13.setText("Rs.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 30, 30));

        pay_print.setBackground(new java.awt.Color(102, 102, 255));
        pay_print.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        pay_print.setText("Print Bill");
        pay_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_printActionPerformed(evt);
            }
        });
        getContentPane().add(pay_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 130, 40));

        pay_clear.setBackground(new java.awt.Color(51, 51, 255));
        pay_clear.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        pay_clear.setText("Clear");
        pay_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_clearActionPerformed(evt);
            }
        });
        getContentPane().add(pay_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 40));

        table_pay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service Name", "Service Type", "Service Cost", "Service Result"
            }
        ));
        table_pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_payMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_pay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 400, 160));

        Payement.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        Payement.setText("Payment");
        getContentPane().add(Payement, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 70, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel15.setText("Rs.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 30, 30));

        pay_payment.setText("0.00");
        pay_payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pay_paymentMouseClicked(evt);
            }
        });
        pay_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_paymentActionPerformed(evt);
            }
        });
        getContentPane().add(pay_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 80, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel14.setText("Sub Total");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 70, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel16.setText("Rs.");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 30, 30));

        pay_subtotal.setText("0.00");
        pay_subtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pay_subtotalMouseClicked(evt);
            }
        });
        pay_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_subtotalActionPerformed(evt);
            }
        });
        getContentPane().add(pay_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 80, 30));

        pay_balance_but.setBackground(new java.awt.Color(102, 102, 255));
        pay_balance_but.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        pay_balance_but.setText("Balance");
        pay_balance_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_balance_butActionPerformed(evt);
            }
        });
        getContentPane().add(pay_balance_but, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 270, -1, 30));

        pay_show1.setBackground(new java.awt.Color(102, 102, 255));
        pay_show1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        pay_show1.setText("Show Payment");
        pay_show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_show1ActionPerformed(evt);
            }
        });
        getContentPane().add(pay_show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 130, 40));

        test_result.setColumns(20);
        test_result.setRows(5);
        jScrollPane2.setViewportView(test_result);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 66, 150, 230));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Test Result", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 180, 280));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pay_p_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_p_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pay_p_lnameActionPerformed

    private void pay_p_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_p_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pay_p_fnameActionPerformed

    private void pay_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pay_balanceActionPerformed

    private void pay_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_printActionPerformed

        payment_mod p = new payment_mod();
        p.pay_adm_id = pay_adm_id.getText();
        p.pay_subtotal = pay_subtotal.getText();
        p.pay_payment = pay_payment.getText();
        p.pay_balance = pay_balance.getText();
        p.print(table_pay);

        /*try {
            // TODO add your handling code here:
          
            int adm_id = 0;
            int pt_id = 0;
            int per_id = 0;
            
            
            ResultSet m = query.thequery_search("select a_id,Patient_patient_id as patient_id from addmission where a_id='"+pay_adm_id.getText()+"'");
            
            
            if(m.next()){
                adm_id = m.getInt("a_id");
                pt_id = m.getInt("patient_id");
               
            }  
            query.thequery("insert into payment(addmission_a_id,sub_total,payment,balance) values('"+adm_id+"','"+pay_subtotal.getText()+"','"+pay_payment.getText()+"','"+pay_balance.getText()+"')");
            
            admission mn = new admission();
            mn.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(payment.class.getName()).log(Level.SEVERE, null, ex);
        }*/

    }//GEN-LAST:event_pay_printActionPerformed

    private void pay_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_clearActionPerformed
        DefaultTableModel model = (DefaultTableModel) table_pay.getModel();
        pay_adm_id.setText("");
        pay_p_fname.setText("");
        pay_p_lname.setText("");
        pay_balance.setText("");
        pay_subtotal.setText("");
        pay_balance.setText("");
        pay_payment.setText("");
        model.setRowCount(0);


    }//GEN-LAST:event_pay_clearActionPerformed

    private void pay_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_mainActionPerformed
        menu mn = new menu();
        mn.setVisible(true);
        close();
    }//GEN-LAST:event_pay_mainActionPerformed

    private void pay_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pay_paymentActionPerformed

    private void pay_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pay_subtotalActionPerformed

    private void pay_balance_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_balance_butActionPerformed
        // TODO add your handling code here:
        double int1 = Double.parseDouble(pay_payment.getText());
        double int2 = Double.parseDouble(pay_subtotal.getText());
        pay_balance.setText(String.valueOf(int1 - int2));
    }//GEN-LAST:event_pay_balance_butActionPerformed

    private void pay_show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_show1ActionPerformed
        
        try {
            payment_mod p = new payment_mod();
            p.pay_adm_id = pay_adm_id.getText();
            double a = p.show(table_pay);
            pay_subtotal.setText(a + "");
            int p_id = 0;
            int per_id = 0;
            String fname =null;
            String lname = null;
            ResultSet d = query.thequery_search("select * from addmission where a_id='" + pay_adm_id.getText() + "'");
            if(d.next()){
                p_id = d.getInt("Patient_patient_id");
            }
            ResultSet e = query.thequery_search("select * from patient where patient_id='" + p_id + "'");
            if(e.next()){
                per_id = e.getInt("person_person_id");
                
            }
            ResultSet w = query.thequery_search("select * from person where person_id='" + per_id + "'");
            if(w.next()){
                fname = w.getString("person_fname");
                lname = w.getString("person_lname");
                
            }
            pay_p_fname.setText(fname);
            pay_p_lname.setText(lname);
            
            /*try {
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) table_pay.getModel();

            int srvc_id = 0;
            double srvc_cost;
            double sum = 0;
            String srvc_name = null;
            String srvc_type = null;
            String srvc_result = null;
            
            ResultSet h = query.thequery_search("select * from service_has_addmission where addmission_a_id='" + pay_adm_id.getText() + "'");
            while(h.next()){
            srvc_id = h.getInt("service_service_id");
            srvc_result = h.getString("service_result");
            ResultSet k = query.thequery_search("select * from service where service_id='" + srvc_id + "'");
            while(k.next()){
            srvc_cost = k.getDouble("service_cost");
            sum = sum+srvc_cost ;
            srvc_name = k.getString("service_name");
            srvc_type = k.getString("service_type");
            
            
            model.addRow(new Object[] {srvc_name,srvc_type,srvc_cost,srvc_result});
            
            
            }
            }
            pay_subtotal.setText(sum+"");
            
            } catch (Exception ex) {
            Logger.getLogger(payment.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_pay_show1ActionPerformed

    private void pay_subtotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pay_subtotalMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_pay_subtotalMouseClicked

    private void pay_paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pay_paymentMouseClicked
        // TODO add your handling code here:
        pay_payment.setText("");
    }//GEN-LAST:event_pay_paymentMouseClicked

    private void table_payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_payMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_pay.getModel();

        int i = table_pay.getSelectedRow();

        if (i >= 0) {
            if (model.getValueAt(i, 3).toString() != null) {
                test_result.setText(model.getValueAt(i, 3).toString());
            }
        }
    }//GEN-LAST:event_table_payMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new payment().setVisible(true);
        });
    }

    private void close() {
        WindowEvent winclosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosing);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Payement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pay_adm_id;
    private javax.swing.JTextField pay_balance;
    private javax.swing.JButton pay_balance_but;
    private javax.swing.JButton pay_clear;
    private javax.swing.JButton pay_main;
    private javax.swing.JTextField pay_p_fname;
    private javax.swing.JTextField pay_p_lname;
    private javax.swing.JTextField pay_payment;
    private javax.swing.JButton pay_print;
    private javax.swing.JButton pay_show1;
    private javax.swing.JTextField pay_subtotal;
    private javax.swing.JTable table_pay;
    private javax.swing.JTextArea test_result;
    // End of variables declaration//GEN-END:variables
}
